#!/bin/bash
#
# Project:      drtm - Dartmoor
# Repository:   https://github.com/cvdg/rdwk/
# Date:         2017-05-24
#
# Author:       Cees van de Griend <c.vande.griend@gmail.com>
# Copyright:    (c) 2017 C.A. van de Griend
#
# Description:  Install as: /etc/cron.daily/drtm
#

# Sanity check, is Dartmoor installed?
if [ -x /opt/drtm/sbin/drtm ] ; then
    LEVEL="unknown"
    WEEKDAY=$(/bin/date +%w)

    # Sunday?
    if [ ${WEEKDAY} -eq 0 ] ; then
        LEVEL="weekly"
    # Nornal day.
    else
        LEVEL="daily"
    fi

    /opt/drtm/sbin/drtm ${LEVEL}
fi
