#!/bin/bash
#
# Update drtm from GitHub
#

DRTM_PID="${BASHPID}"
DRTM_LOCKFILE="/var/opt/drtm/run/drtm.lock"



if [ ${EUID} -ne 0 ] ; then
    echo "Error: You're not root"
    exit 1
fi

if [ ! -d /opt/drtm ] ; then
    echo "Error: Dartmoor is not installed"
    exit 1
fi

cd /opt/drtm



if [ ! -d /var/opt/drtm/log ] ; then
    mkdir -p /var/opt/drtm/log
fi

if [ ! -d /var/opt/drtm/run ] ; then
    mkdir -p /var/opt/drtm/run
fi



function drtm_log {
    DATE=$(date '+%Y%m%d')
    DATETIME=$(date '+%Y-%m-%d %H:%M:%S')

    echo "${DATETIME} drtm[${DRTM_PID}] $*" >> /var/opt/drtm/log/drtm-${DATE}.log
}



function drtm_unlock {
    drtm_log "unlock"

    rm -f ${DRTM_LOCKFILE}
}



function drtm_lock {
    drtm_log "lock"

    if [ -f ${DRTM_LOCKFILE} ] ; then
        drtm_log "Error: lockfile ${DRTM_LOCKFILE} exists"
        exit 1
    fi

    echo ${DRTM_PID} > ${DRTM_LOCKFILE}
}



function drtm_upgrade {
    drtm_log "upgrade"

    DATE=$(date '+%Y%m%d')
    DATETIME=$(date '+%Y-%m-%d %H:%M:%S')

    (  /usr/bin/apt-get -y update \
    && /usr/bin/apt-get -y upgrade \
    && /usr/bin/apt-get -y autoremove \
    && /usr/bin/apt-get -y autoclean ) \
    | /usr/bin/tee -a /var/opt/drtm/log/drtm-${DATE}.log 2>&1
}



function drtm_maintenance {
    drtm_log "maintenance"

    find /var/opt/drtm/log -type f -ctime +1 -name '*.log' -exec gzip {} \;
}



#
# Main
#

drtm_log "start drtm upgrade"
drtm_lock

trap drtm_unlock EXIT

drtm_upgrade

drtm_maintenance
drtm_log "finish"

exit 0
